#!/bin/bash

########################################################################
# Copyright (C) 2013 - 2020 : Kathrin Hanauer                          #
#                                                                      #
# This file is part of Algora.                                         #
#                                                                      #
# Algora is free software: you can redistribute it and/or modify       #
# it under the terms of the GNU General Public License as published by #
# the Free Software Foundation, either version 3 of the License, or    #
# (at your option) any later version.                                  #
#                                                                      #
# Algora is distributed in the hope that it will be useful,            #
# but WITHOUT ANY WARRANTY; without even the implied warranty of       #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        #
# GNU General Public License for more details.                         #
#                                                                      #
# You should have received a copy of the GNU General Public License    #
# along with Algora.  If not, see <http://www.gnu.org/licenses/>.      #
#                                                                      #
# Contact information:                                                 #
#   http://algora.xaikal.org                                           #
########################################################################

set -e
ROOT_DIR=$(cd "$(dirname "$0")" && pwd)

export QT_SELECT=qt5
PRO_FILE="Subgraphen.pro"

CLEAN=0
EXTRA_ARGS=""
QMAKE=""
SPEC="linux-g++-64"
REFERENCE_CODE=ON

function usage() {
    echo "Usage: $0 [ --qmake <path/to/qmake> ] [ --without-reference-code ] [ -c | --clean ] [ -g | --general ] [ -d | --debugsymbols] [ -p | --profiling] [ --clang ] [ -C | --compiler <compiler> ] [ -L | --linker <linker> ]"
}

while [[ $# -gt 0 ]]
do
case $1 in
    --without-reference-code)
    REFERENCE_CODE=OFF
    shift
    ;;
    --qmake)
    QMAKE="$2"
    shift
    shift
    ;;
    -c|--clean)
    CLEAN=1
    shift
    ;;
    -g|--general)
    EXTRA_ARGS="${EXTRA_ARGS} CONFIG+=general" # do not optimize for this cpu only
    shift
    ;;
    -d|--debugsymbols)
    EXTRA_ARGS="${EXTRA_ARGS} CONFIG+=debugsymbols" # add debug symbols in release version
    shift
    ;;
    -p|--profiling)
    EXTRA_ARGS="${EXTRA_ARGS} CONFIG+=profiling" # enable profiling code
    shift
    ;;
    --clang)
    SPEC="linux-clang"
    shift
    ;;
    -C|--compiler)
    EXTRA_ARGS="${EXTRA_ARGS} QMAKE_CXX=$2"
    shift
    shift
    ;;
    -L|--linker)
    EXTRA_ARGS="${EXTRA_ARGS} QMAKE_LINK=$2"
    shift
    shift
    ;;
    -h|--help)
    usage
    exit 0
    ;;
    --)
    shift
    break
    ;;
    *)
    echo "Ignoring unknown option $1. Run $0 -h for help."
    shift
    ;;
esac
done

[ -z "${QMAKE}" ] && QMAKE=$(which qmake 2>/dev/null) && echo "Using \"${QMAKE}\" for \"qmake\"."
[ -z "${QMAKE}" ] && QMAKE=$(which qmake-qt5 2>/dev/null) && echo "Using \"${QMAKE}\" for \"qmake\"."
[ -n "${QMAKE}" ] || eval 'echo "Binary \"qmake\" or \"qmake-qt5\" not found. Please specify its location explicitly via --qmake <path/to/qmake>." 1>&2; exit 1'
[ -x "${QMAKE}" ] || eval 'echo "\"${QMAKE}\" is not an executable. Please specify the location of the qmake binary explicitly via --qmake <path/to/qmake>." 1>&2; exit 1'

ALGORA_ARCHIVE="${ROOT_DIR}/deps/algora-source.zip"
ALGORA_CORE="${ROOT_DIR}/deps/AlgoraCore"
ALGORA_DYN="${ROOT_DIR}/deps/AlgoraDyn"
if [ ! -f "${ALGORA_CORE}/src/AlgoraCore.pro" ] || [ ! -f "${ALGORA_DYN}/src/AlgoraDyn.pro" ]; then
    [ -f "${ALGORA_ARCHIVE}" ] || { echo "Missing ${ALGORA_ARCHIVE}" >&2; exit 1; }
    echo "Unpacking Algora sources into deps/..."
    unzip -n -q "${ALGORA_ARCHIVE}" -d "${ROOT_DIR}/deps"
fi
if [ "$(git -C "${ALGORA_CORE}" rev-parse HEAD 2>/dev/null)" != "b8a94f0fb845b4aa8b9d1f09cee8174c804eeaa4" ] ||
   [ "$(git -C "${ALGORA_DYN}" rev-parse HEAD 2>/dev/null)" != "41d8f4feb86f553ae7a26d616d2cb6b146524f1c" ]; then
    echo "Algora sources in deps/ do not match bundled Core v1.4 and Dyn v1.2" >&2
    exit 1
fi

for library in AlgoraCore AlgoraDyn; do
    library_dir="${ROOT_DIR}/deps/${library}"
    if [ ! -f "${library_dir}/build/Debug/lib${library}.a" ] ||
       [ ! -f "${library_dir}/build/Release/lib${library}.a" ]; then
        echo "Compiling ${library}..."
        (cd "${library_dir}" && ./easyCompile --qmake "${QMAKE}")
        [ -f "${library_dir}/build/Debug/lib${library}.a" ] &&
        [ -f "${library_dir}/build/Release/lib${library}.a" ] || {
            echo "${library} did not produce both Debug and Release libraries" >&2
            exit 1
        }
    fi
done

if [ "$REFERENCE_CODE" = ON ]; then
    bash "${ROOT_DIR}/fetch_reference_sources.sh"
fi

QMAKE_ARGS="-r -spec ${SPEC} REFERENCE_CODE=${REFERENCE_CODE} ${EXTRA_ARGS} $@"
QMAKE_ARGS_DEBUG="CONFIG+=debug"


CUR_DIR="${ROOT_DIR}"
BUILD_DIR="${CUR_DIR}/build"
BUILD_DIR_DEBUG="${BUILD_DIR}/Debug"
BUILD_DIR_RELEASE="${BUILD_DIR}/Release"

PRO_PATH="${CUR_DIR}/src/${PRO_FILE}"

if [ "${CLEAN}" -gt 0 ]
then
  echo "Removing build directory as requested..."
  rm -rf ${BUILD_DIR}
fi

echo "Creating build paths if necessary..."
mkdir -p "${BUILD_DIR_DEBUG}"
mkdir -p "${BUILD_DIR_RELEASE}"

echo "Compiling debug version..."
cd "${BUILD_DIR_DEBUG}"
"${QMAKE}" "${PRO_PATH}" ${QMAKE_ARGS} ${QMAKE_ARGS_DEBUG}
make


echo "Compiling release version..."
cd "${BUILD_DIR_RELEASE}"
"${QMAKE}" "${PRO_PATH}" ${QMAKE_ARGS}
make

cd "${CUR_DIR}"
